name: sync-openclash

on:
  schedule:
    - cron:  "* */12 * * *"
  workflow_dispatch:
  watch:
    types: started

jobs:
  repo-sync:
    runs-on: ubuntu-latest
    if: github.event.repository.owner.id == github.event.sender.id
    timeout-minutes: 2
    steps:
      - uses: actions/checkout@v2
      - name: init
        run: |
          git config --global user.name 'GitHub Actions' && git config --global user.email 'noreply@github.com'
      - name: git clone vernesong/OpenClash
        run: |
          git clone https://github.com/vernesong/OpenClash OpenClash1
      - name: git push zyipk/packages
        uses: ad-m/github-push-action@v0.6.0
        with:
          directory: packages/Openclash1
          github_token: ${{ secrets.PAT }}
          branch: Openclash
          force: true
